this commit will add task 3
andraimoraru/andras_news pull request #3
Opened 2023-08-15 13:03 UTC by andraimoraru

2023-08-15 15:07 UTC, itsaliabdallah requested changes
Nice work on this one.
Just move your logic for the /api model into the controller and rework the test and you'll be good to go.

2023-08-15 15:07 UTC, itsaliabdallah commented on __tests__/app.test.js
> +                    expect(key).toContain('GET /api');
Could we better test that the return looks like the endpoint object.

2023-08-15 15:07 UTC, aloush-dev commented on app.js
> +    response.status(404).send({ msg : 'Not found'})
Nice!

2023-08-15 15:07 UTC, itsaliabdallah commented on models/api.models.js
> +};
Nice this logic is a good way to go about this but It should be in the controller rather than the model as we are not interacting with the database.

2023-08-16 12:25 UTC, leekli approved these changes
Approved.

2023-08-16 12:28 UTC, merged